export function bootstrapFiles(spec) {
  const pkg = spec.project.packageName;
  const artifact = spec.project.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  const appClass = spec.project.name.replace(/[^a-zA-Z0-9]+/g, ' ').trim().split(/\s+/).map((x) => x[0].toUpperCase() + x.slice(1)).join('') || 'Application';
  const db = spec.project.database === 'mysql';
  const dbUrl = db ? 'jdbc:mysql://localhost:3306/${DB_NAME:enterprise_db}?createDatabaseIfNotExist=true&serverTimezone=UTC' : 'jdbc:postgresql://localhost:5432/${DB_NAME:enterprise_db}';
  const driver = db ? 'com.mysql.cj.jdbc.Driver' : 'org.postgresql.Driver';
  const dbService = db ? `  db:\n    image: mysql:8.4\n    environment:\n      MYSQL_DATABASE: enterprise_db\n      MYSQL_USER: app\n      MYSQL_PASSWORD: app\n      MYSQL_ROOT_PASSWORD: root\n    ports:\n      - "3306:3306"` : `  db:\n    image: postgres:17\n    environment:\n      POSTGRES_DB: enterprise_db\n      POSTGRES_USER: app\n      POSTGRES_PASSWORD: app\n    ports:\n      - "5432:5432"`;

  return {
    'backend/pom.xml': `<?xml version="1.0" encoding="UTF-8"?><project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-parent</artifactId><version>3.5.7</version><relativePath/></parent><groupId>${pkg}</groupId><artifactId>${artifact}</artifactId><version>0.1.0</version><properties><java.version>${spec.project.java}</java.version></properties><dependencies><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-web</artifactId></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-validation</artifactId></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-data-jpa</artifactId></dependency><dependency><groupId>org.flywaydb</groupId><artifactId>flyway-core</artifactId></dependency>${db ? '<dependency><groupId>com.mysql</groupId><artifactId>mysql-connector-j</artifactId><scope>runtime</scope></dependency>' : '<dependency><groupId>org.postgresql</groupId><artifactId>postgresql</artifactId><scope>runtime</scope></dependency>'}<dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-security</artifactId></dependency><dependency><groupId>org.springdoc</groupId><artifactId>springdoc-openapi-starter-webmvc-ui</artifactId><version>2.8.13</version></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-test</artifactId><scope>test</scope></dependency></dependencies><build><plugins><plugin><groupId>org.springframework.boot</groupId><artifactId>spring-boot-maven-plugin</artifactId></plugin></plugins></build></project>`,
    [`backend/src/main/java/${pkg.replaceAll('.', '/')}/${appClass}Application.java`]: `package ${pkg};\n\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\n\n@SpringBootApplication\npublic class ${appClass}Application {\n    public static void main(String[] args) { SpringApplication.run(${appClass}Application.class, args); }\n}\n`,
    'backend/src/main/resources/application.yml': `spring:\n  application:\n    name: ${artifact}\n  datasource:\n    url: ${dbUrl}\n    username: \${DB_USER:app}\n    password: \${DB_PASSWORD:app}\n    driver-class-name: ${driver}\n  jpa:\n    hibernate:\n      ddl-auto: validate\n    open-in-view: false\n  flyway:\n    enabled: true\nserver:\n  port: \${SERVER_PORT:8080}\nspringdoc:\n  swagger-ui:\n    path: /swagger-ui.html\n`,
    [`backend/src/main/java/${pkg.replaceAll('.', '/')}/shared/security/SecurityConfig.java`]: `package ${pkg}.shared.security;\n\nimport org.springframework.context.annotation.Bean;\nimport org.springframework.context.annotation.Configuration;\nimport org.springframework.security.config.annotation.web.builders.HttpSecurity;\nimport org.springframework.security.web.SecurityFilterChain;\n\n@Configuration\npublic class SecurityConfig {\n    @Bean\n    SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {\n        return http.csrf(csrf -> csrf.disable()).authorizeHttpRequests(auth -> auth.requestMatchers("/swagger-ui/**", "/v3/api-docs/**").permitAll().anyRequest().authenticated()).build();\n    }\n}\n`,
    'backend/Dockerfile': `FROM maven:3.9-eclipse-temurin-17 AS build\nWORKDIR /app\nCOPY pom.xml .\nCOPY src ./src\nRUN mvn -B -DskipTests package\nFROM eclipse-temurin:17-jre\nWORKDIR /app\nCOPY --from=build /app/target/*.jar app.jar\nEXPOSE 8080\nENTRYPOINT ["java", "-jar", "app.jar"]\n`,
    'docker-compose.yml': `services:\n${dbService}\n  backend:\n    build: ./backend\n    environment:\n      DB_NAME: enterprise_db\n      DB_USER: app\n      DB_PASSWORD: app\n    ports:\n      - "8080:8080"\n    depends_on:\n      - db\n`,
    'frontend/package.json': `{"private":true,"type":"module","scripts":{"dev":"vite","build":"vite build","test":"vitest run"},"dependencies":{"@emotion/react":"latest","@emotion/styled":"latest","@mui/material":"latest","axios":"latest","react":"latest","react-dom":"latest","react-router-dom":"latest"},"devDependencies":{"@vitejs/plugin-react":"latest","vite":"latest","vitest":"latest"}}`,
    'frontend/vite.config.js': `import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\nexport default defineConfig({ plugins: [react()] });\n`,
    'frontend/index.html': `<!doctype html><html><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>${spec.project.name}</title></head><body><div id="root"></div><script type="module" src="/src/main.jsx"></script></body></html>`,
    'frontend/src/main.jsx': `import React from 'react';\nimport { createRoot } from 'react-dom/client';\nimport { BrowserRouter } from 'react-router-dom';\nimport { CssBaseline, ThemeProvider, createTheme } from '@mui/material';\nimport App from './App.jsx';\ncreateRoot(document.getElementById('root')).render(<ThemeProvider theme={createTheme()}><CssBaseline/><BrowserRouter><App/></BrowserRouter></ThemeProvider>);\n`,
    'frontend/src/App.jsx': `import { AppBar, Box, Container, Toolbar, Typography } from '@mui/material';\nexport default function App() { return <><AppBar position="static"><Toolbar><Typography>${spec.project.name}</Typography></Toolbar></AppBar><Container sx={{py:4}}><Box><Typography variant="h3">Application Ready</Typography><Typography color="text.secondary">Generated enterprise application.</Typography></Box></Container></>; }\n`,
    '.github/workflows/build.yml': `name: Build Application\n\non:\n  push:\n  pull_request:\n\njobs:\n  backend:\n    runs-on: ubuntu-latest\n    defaults:\n      run:\n        working-directory: backend\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-java@v4\n        with:\n          distribution: temurin\n          java-version: '17'\n          cache: maven\n      - run: mvn -B test\n`,
    'generated/bootstrap-manifest.json': JSON.stringify({ project: spec.project.name, backend: 'Spring Boot', frontend: 'React + Vite + MUI', database: spec.project.database, security: spec.architecture.security, migration: spec.architecture.migration }, null, 2)
  };
}
