import React, { useMemo, useState } from 'react';
import { Box, CssBaseline, Drawer, List, ListItemButton, ListItemIcon, ListItemText, AppBar, Toolbar, Typography, IconButton, Avatar, Paper, Grid, Chip, Button, TextField, InputAdornment, Divider } from '@mui/material';
import DashboardRoundedIcon from '@mui/icons-material/DashboardRounded';
import AppsRoundedIcon from '@mui/icons-material/AppsRounded';
import TableViewRoundedIcon from '@mui/icons-material/TableViewRounded';
import PeopleAltRoundedIcon from '@mui/icons-material/PeopleAltRounded';
import SecurityRoundedIcon from '@mui/icons-material/SecurityRounded';
import AccountTreeRoundedIcon from '@mui/icons-material/AccountTreeRounded';
import SettingsRoundedIcon from '@mui/icons-material/SettingsRounded';
import AutoAwesomeRoundedIcon from '@mui/icons-material/AutoAwesomeRounded';
import SearchRoundedIcon from '@mui/icons-material/SearchRounded';
import NotificationsNoneRoundedIcon from '@mui/icons-material/NotificationsNoneRounded';

const drawerWidth = 248;
const nav = [
  ['Dashboard', DashboardRoundedIcon], ['Applications', AppsRoundedIcon], ['Modules', TableViewRoundedIcon],
  ['Users', PeopleAltRoundedIcon], ['Roles & Permissions', SecurityRoundedIcon], ['Relationships', AccountTreeRoundedIcon], ['Settings', SettingsRoundedIcon],
];
const stats = [['Applications', '12', '+3 this month'], ['Modules', '86', '+14 this month'], ['Active Users', '248', '+8.4%'], ['Generated Builds', '39', '+12.5%']];
const recent = [['Customer Management', 'CRM Suite', 'Ready', '2 min ago'], ['Employee Portal', 'HRMS', 'Building', '8 min ago'], ['Inventory Control', 'Operations', 'Ready', '21 min ago'], ['Sales Pipeline', 'CRM Suite', 'Draft', '1 hr ago']];

export default function App() {
  const [active, setActive] = useState('Dashboard');
  const [search, setSearch] = useState('');
  const filtered = useMemo(() => recent.filter(r => r.join(' ').toLowerCase().includes(search.toLowerCase())), [search]);
  return <Box sx={{ display: 'flex', minHeight: '100vh', bgcolor: '#f5f7fb' }}><CssBaseline />
    <Drawer variant="permanent" sx={{ width: drawerWidth, flexShrink: 0, '& .MuiDrawer-paper': { width: drawerWidth, boxSizing: 'border-box', bgcolor: '#111827', color: '#dbe4f0', borderRight: '1px solid #202a3a' } }}>
      <Box sx={{ px: 2.5, py: 2.5, display: 'flex', alignItems: 'center', gap: 1.5 }}><Box sx={{ width: 38, height: 38, borderRadius: 2, display: 'grid', placeItems: 'center', bgcolor: '#2563eb', color: '#fff', fontWeight: 900 }}>EA</Box><Box><Typography sx={{ fontWeight: 800, lineHeight: 1.1, color: '#fff' }}>Enterprise</Typography><Typography sx={{ fontSize: 12, color: '#94a3b8' }}>App Builder</Typography></Box></Box>
      <Divider sx={{ borderColor: '#263244', mb: 1.5 }} /><Typography sx={{ px: 2.5, mb: 1, fontSize: 11, fontWeight: 800, letterSpacing: 1, color: '#64748b' }}>WORKSPACE</Typography>
      <List sx={{ px: 1.2 }}>{nav.map(([label, Icon]) => <ListItemButton key={label} selected={active === label} onClick={() => setActive(label)} sx={{ borderRadius: 1.8, mb: .5, color: '#aebbd0', '& .MuiListItemIcon-root': { color: 'inherit', minWidth: 38 }, '&.Mui-selected': { bgcolor: '#1d4ed8', color: '#fff' }, '&.Mui-selected:hover': { bgcolor: '#1e40af' }, '&:hover': { bgcolor: '#182235' } }}><ListItemIcon><Icon fontSize="small" /></ListItemIcon><ListItemText primary={label} primaryTypographyProps={{ fontSize: 13.5, fontWeight: active === label ? 700 : 500 }} /></ListItemButton>)}</List>
      <Box sx={{ mt: 'auto', p: 2 }}><Paper sx={{ p: 1.7, bgcolor: '#172033', color: '#dbe4f0', border: '1px solid #263244', borderRadius: 2.5 }}><AutoAwesomeRoundedIcon sx={{ fontSize: 20, color: '#60a5fa' }} /><Typography sx={{ fontSize: 13, fontWeight: 700, mt: .7 }}>Build faster</Typography><Typography sx={{ fontSize: 11.5, color: '#94a3b8', mt: .4 }}>Generate production-ready apps from one specification.</Typography></Paper></Box>
    </Drawer>
    <Box component="main" sx={{ flexGrow: 1 }}><AppBar position="sticky" elevation={0} sx={{ bgcolor: 'rgba(255,255,255,.94)', color: '#0f172a', borderBottom: '1px solid #e5e7eb', backdropFilter: 'blur(10px)' }}><Toolbar sx={{ minHeight: 70 }}><Box sx={{ flexGrow: 1 }}><Typography sx={{ fontWeight: 800, fontSize: 18 }}>{active}</Typography><Typography sx={{ fontSize: 12, color: '#64748b' }}>Enterprise App Builder workspace</Typography></Box><TextField size="small" placeholder="Search" value={search} onChange={e => setSearch(e.target.value)} sx={{ width: 220, mr: 1.5, '& .MuiOutlinedInput-root': { bgcolor: '#f8fafc', borderRadius: 2 } }} InputProps={{ startAdornment: <InputAdornment position="start"><SearchRoundedIcon fontSize="small" /></InputAdornment> }} /><IconButton sx={{ mr: 1 }}><NotificationsNoneRoundedIcon /></IconButton><Avatar sx={{ width: 34, height: 34, bgcolor: '#2563eb', fontSize: 13 }}>DG</Avatar></Toolbar></AppBar>
      <Box sx={{ p: { xs: 2, md: 3.5 } }}><Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', mb: 3 }}><Box><Typography variant="h4" sx={{ fontWeight: 850, letterSpacing: -.7 }}>Good afternoon</Typography><Typography sx={{ color: '#64748b', mt: .5 }}>Build, manage and deploy enterprise applications from one workspace.</Typography></Box><Button variant="contained" startIcon={<AutoAwesomeRoundedIcon />} sx={{ borderRadius: 2, px: 2.2, py: 1.1, textTransform: 'none', fontWeight: 800, boxShadow: 'none' }}>Generate Application</Button></Box>
        <Grid container spacing={2} sx={{ mb: 3 }}>{stats.map(([title, value, trend]) => <Grid item xs={12} sm={6} md={3} key={title}><Paper sx={{ p: 2.4, border: '1px solid #e5e7eb', borderRadius: 2.5, boxShadow: '0 1px 2px rgba(15,23,42,.03)' }}><Typography sx={{ color: '#64748b', fontSize: 12.5, fontWeight: 700 }}>{title}</Typography><Typography sx={{ fontSize: 30, fontWeight: 850, mt: .7 }}>{value}</Typography><Chip label={trend} size="small" sx={{ mt: 1, bgcolor: '#ecfdf5', color: '#047857', fontWeight: 700, fontSize: 10.5 }} /></Paper></Grid>)}</Grid>
        <Grid container spacing={2.5}><Grid item xs={12} md={8}><Paper sx={{ border: '1px solid #e5e7eb', borderRadius: 2.5, overflow: 'hidden' }}><Box sx={{ p: 2.4, display: 'flex', justifyContent: 'space-between' }}><Box><Typography sx={{ fontWeight: 800 }}>Recent applications</Typography><Typography sx={{ color: '#64748b', fontSize: 12 }}>Latest projects and generator activity</Typography></Box><Button size="small" sx={{ textTransform: 'none' }}>View all</Button></Box><Box sx={{ overflowX: 'auto' }}><table style={{ width: '100%', borderCollapse: 'collapse' }}><thead><tr>{['Application','Type','Status','Updated'].map(h => <th key={h} style={{ textAlign: 'left', padding: '12px 20px', fontSize: 11, color: '#64748b', background: '#f8fafc', borderTop: '1px solid #eef2f7', borderBottom: '1px solid #eef2f7' }}>{h}</th>)}</tr></thead><tbody>{filtered.map((r, i) => <tr key={i}>{r.map((c,j) => <td key={j} style={{ padding: '15px 20px', fontSize: 13, color: j === 0 ? '#0f172a' : '#475569', fontWeight: j === 0 ? 700 : 500, borderBottom: '1px solid #eef2f7' }}>{j === 2 ? <Chip label={c} size="small" sx={{ fontSize: 10.5, fontWeight: 700 }} /> : c}</td>)}</tr>)}</tbody></table></Box></Paper></Grid><Grid item xs={12} md={4}><Paper sx={{ p: 2.5, border: '1px solid #e5e7eb', borderRadius: 2.5 }}><Typography sx={{ fontWeight: 800 }}>Build activity</Typography><Typography sx={{ color: '#64748b', fontSize: 12, mb: 2 }}>Generator usage this week</Typography><Box sx={{ height: 170, display: 'flex', alignItems: 'flex-end', gap: 1.1 }}>{[45,70,55,90,65,105,82].map((h,i)=><Box key={i} sx={{ flex: 1, height: h, bgcolor: i === 5 ? '#2563eb' : '#bfdbfe', borderRadius: '6px 6px 2px 2px' }} />)}</Box><Box sx={{ display: 'flex', justifyContent: 'space-between', mt: 1, color: '#94a3b8', fontSize: 10 }}>{['M','T','W','T','F','S','S'].map((d,i)=><span key={i}>{d}</span>)}</Box></Paper></Grid></Grid>
      </Box></Box>
  </Box>;
}
