import fs from 'node:fs/promises';
import path from 'node:path';

const args = process.argv.slice(2);
const validateOnly = args.includes('--validate');
const specArg = args.find((arg) => arg.startsWith('--spec='));
const outputArg = args.find((arg) => arg.startsWith('--output='));

const defaultSpec = {
  version: '0.4.0',
  project: { name: 'Enterprise CRM', packageName: 'com.example.crm', database: 'mysql', java: '17' },
  architecture: { backend: 'spring-boot', frontend: 'react-mui', security: 'jwt-rbac', migration: 'flyway' },
  modules: [
    { name: 'Company', entity: 'Company', fields: 'companyCode, companyName, email, phone, city, state, country, active' },
    { name: 'Branch', entity: 'Branch', fields: 'branchCode, branchName, city, state, country, active' }
  ]
};

const spec = specArg ? JSON.parse(await fs.readFile(specArg.slice(7), 'utf8')) : defaultSpec;
validateSpec(spec);
if (validateOnly) {
  console.log('ProjectSpec validation passed.');
  process.exit(0);
}

const output = outputArg ? outputArg.slice(9) : path.resolve(process.cwd(), 'generated-app');
await fs.rm(output, { recursive: true, force: true });
await generate(spec, output);
console.log(`Generated ${spec.project.name} at ${output}`);

function validateSpec(value) {
  if (!value?.project?.name?.trim()) throw new Error('project.name is required');
  if (!/^[a-zA-Z_][a-zA-Z0-9_.]*$/.test(value.project.packageName || '')) throw new Error('project.packageName must be a valid Java package');
  if (!['mysql', 'postgresql'].includes(value.project.database)) throw new Error('project.database must be mysql or postgresql');
  if (!Array.isArray(value.modules) || value.modules.length === 0) throw new Error('At least one module is required');
  for (const module of value.modules) {
    if (!module.name || !module.entity || !module.fields) throw new Error('Every module requires name, entity and fields');
  }
}

async function write(root, file, content) {
  const target = path.join(root, file);
  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, content, 'utf8');
}

function className(value) { return value.replace(/[^a-zA-Z0-9]+/g, ' ').trim().split(/\s+/).map((p) => p[0].toUpperCase() + p.slice(1)).join('') || 'Application'; }
function fieldName(value) { const c = className(value); return c ? c[0].toLowerCase() + c.slice(1) : c; }
function tableName(value) { return fieldName(value).replace(/[A-Z]/g, (m) => `_${m.toLowerCase()}`).replace(/^_/, ''); }
function packagePath(pkg) { return pkg.replaceAll('.', '/'); }

async function generate(spec, root) {
  const pkg = spec.project.packageName;
  const appClass = `${className(spec.project.name)}Application`;
  const artifact = fieldName(spec.project.name).toLowerCase();
  const mysql = spec.project.database === 'mysql';

  await write(root, 'README.md', `# ${spec.project.name}\n\nGenerated by Enterprise App Builder.\n\n## Run\n\n1. Start the database: \\`docker compose up -d db\\`\n2. Start backend: \\`cd backend && mvn spring-boot:run\\`\n3. Start frontend: \\`cd frontend && npm install && npm run dev\\`\n`);
  await write(root, 'backend/pom.xml', pom(pkg, artifact, spec.project.java, mysql));
  await write(root, `backend/src/main/java/${packagePath(pkg)}/${appClass}.java`, `package ${pkg};\n\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\n\n@SpringBootApplication\npublic class ${appClass} {\n  public static void main(String[] args) { SpringApplication.run(${appClass}.class, args); }\n}\n`);
  await write(root, 'backend/src/main/resources/application.yml', applicationYml(spec, artifact, mysql));
  await write(root, `backend/src/main/java/${packagePath(pkg)}/shared/security/SecurityConfig.java`, securityConfig(pkg));
  await write(root, 'frontend/package.json', frontendPackage());
  await write(root, 'frontend/vite.config.js', "import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\nexport default defineConfig({ plugins: [react()] });\n");
  await write(root, 'frontend/index.html', '<div id="root"></div><script type="module" src="/src/main.jsx"></script>');
  await write(root, 'frontend/src/main.jsx', "import React from 'react'; import { createRoot } from 'react-dom/client'; import App from './App.jsx'; createRoot(document.getElementById('root')).render(<App />);\n");
  await write(root, 'frontend/src/App.jsx', `import { Typography, Container } from '@mui/material';\nexport default function App() { return <Container sx={{ py: 6 }}><Typography variant="h3">${spec.project.name}</Typography><Typography>Generated enterprise application.</Typography></Container>; }\n`);

  const migrationParts = [];
  let version = 1;
  for (const module of spec.modules) {
    const entity = className(module.entity);
    const segment = fieldName(module.name);
    const fields = module.fields.split(',').map((f) => f.trim()).filter(Boolean);
    const columns = fields.map((f) => `${tableName(f)} VARCHAR(255)`).join(',\n    ');
    migrationParts.push(`CREATE TABLE ${tableName(module.entity)} (\n    id BIGINT NOT NULL AUTO_INCREMENT,\n    ${columns},\n    active BOOLEAN NOT NULL DEFAULT TRUE,\n    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    updated_at TIMESTAMP NULL,\n    PRIMARY KEY (id)\n);`);
    const base = `backend/src/main/java/${packagePath(pkg)}/module/${segment}`;
    await write(root, `${base}/entity/${entity}.java`, entityTemplate(pkg, segment, entity, fields));
    await write(root, `${base}/repository/${entity}Repository.java`, `package ${pkg}.module.${segment}.repository;\n\nimport ${pkg}.module.${segment}.entity.${entity};\nimport org.springframework.data.jpa.repository.JpaRepository;\npublic interface ${entity}Repository extends JpaRepository<${entity}, Long> {}\n`);
    await write(root, `${base}/dto/${entity}Request.java`, dtoTemplate(pkg, segment, entity, fields));
    await write(root, `${base}/service/${entity}Service.java`, serviceTemplate(pkg, segment, entity));
    await write(root, `${base}/controller/${entity}Controller.java`, controllerTemplate(pkg, segment, entity));
    await write(root, `frontend/src/modules/${segment}/${entity}List.jsx`, frontendModuleTemplate(entity, segment));
    version++;
  }
  await write(root, 'backend/src/main/resources/db/migration/V1__initial_schema.sql', migrationParts.join('\n\n'));
  await write(root, 'docker-compose.yml', compose(mysql));
  await write(root, 'backend/Dockerfile', 'FROM maven:3.9-eclipse-temurin-17 AS build\nWORKDIR /app\nCOPY pom.xml .\nCOPY src ./src\nRUN mvn -B -DskipTests package\nFROM eclipse-temurin:17-jre\nWORKDIR /app\nCOPY --from=build /app/target/*.jar app.jar\nEXPOSE 8080\nENTRYPOINT ["java","-jar","app.jar"]\n');
  await write(root, 'generated/project-spec.json', JSON.stringify(spec, null, 2));
}

function pom(pkg, artifact, java, mysql) { return `<?xml version="1.0" encoding="UTF-8"?><project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-parent</artifactId><version>3.5.7</version><relativePath/></parent><groupId>${pkg}</groupId><artifactId>${artifact}</artifactId><version>0.1.0</version><properties><java.version>${java}</java.version></properties><dependencies><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-web</artifactId></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-data-jpa</artifactId></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-validation</artifactId></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-security</artifactId></dependency><dependency><groupId>org.flywaydb</groupId><artifactId>flyway-core</artifactId></dependency>${mysql ? '<dependency><groupId>com.mysql</groupId><artifactId>mysql-connector-j</artifactId><scope>runtime</scope></dependency>' : '<dependency><groupId>org.postgresql</groupId><artifactId>postgresql</artifactId><scope>runtime</scope></dependency>'}</dependencies><build><plugins><plugin><groupId>org.springframework.boot</groupId><artifactId>spring-boot-maven-plugin</artifactId></plugin></plugins></build></project>`; }
function applicationYml(s, artifact, mysql) { const db = mysql ? 'mysql' : 'postgresql'; const url = mysql ? 'jdbc:mysql://localhost:3306/${DB_NAME:enterprise_db}?createDatabaseIfNotExist=true&serverTimezone=UTC' : 'jdbc:postgresql://localhost:5432/${DB_NAME:enterprise_db}'; return `spring:\n  application:\n    name: ${artifact}\n  datasource:\n    url: ${url}\n    username: ${'${DB_USER:app}'}\n    password: ${'${DB_PASSWORD:app}'}\n  jpa:\n    hibernate:\n      ddl-auto: validate\n    open-in-view: false\n  flyway:\n    enabled: true\nserver:\n  port: ${'${SERVER_PORT:8080}'}\n`; }
function securityConfig(pkg) { return `package ${pkg}.shared.security;\n\nimport org.springframework.context.annotation.*;\nimport org.springframework.security.config.annotation.web.builders.HttpSecurity;\nimport org.springframework.security.web.SecurityFilterChain;\n\n@Configuration\npublic class SecurityConfig {\n  @Bean SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {\n    return http.csrf(csrf -> csrf.disable()).authorizeHttpRequests(auth -> auth.requestMatchers("/error").permitAll().anyRequest().permitAll()).build();\n  }\n}\n`; }
function entityTemplate(pkg, segment, entity, fields) { return `package ${pkg}.module.${segment}.entity;\n\nimport jakarta.persistence.*;\n\n@Entity @Table(name="${tableName(entity)}")\npublic class ${entity} {\n  @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id;\n${fields.map((f) => `  private String ${fieldName(f)};`).join('\n')}\n  private Boolean active = true;\n  public Long getId(){return id;}\n}\n`; }
function dtoTemplate(pkg, segment, entity, fields) { return `package ${pkg}.module.${segment}.dto;\n\npublic record ${entity}Request(${fields.map((f) => `String ${fieldName(f)}`).join(', ')}) {}\n`; }
function serviceTemplate(pkg, segment, entity) { return `package ${pkg}.module.${segment}.service;\n\nimport ${pkg}.module.${segment}.entity.${entity};\nimport ${pkg}.module.${segment}.repository.${entity}Repository;\nimport org.springframework.stereotype.Service;\nimport java.util.List;\n\n@Service public class ${entity}Service {\n  private final ${entity}Repository repository;\n  public ${entity}Service(${entity}Repository repository){this.repository=repository;}\n  public List<${entity}> findAll(){return repository.findAll();}\n  public ${entity} save(${entity} entity){return repository.save(entity);}\n}\n`; }
function controllerTemplate(pkg, segment, entity) { return `package ${pkg}.module.${segment}.controller;\n\nimport ${pkg}.module.${segment}.entity.${entity};\nimport ${pkg}.module.${segment}.service.${entity}Service;\nimport org.springframework.web.bind.annotation.*;\nimport java.util.List;\n\n@RestController @RequestMapping("/api/v1/${segment}") public class ${entity}Controller {\n  private final ${entity}Service service;\n  public ${entity}Controller(${entity}Service service){this.service=service;}\n  @GetMapping public List<${entity}> findAll(){return service.findAll();}\n  @PostMapping public ${entity} create(@RequestBody ${entity} entity){return service.save(entity);}\n}\n`; }
function frontendPackage() { return '{"private":true,"type":"module","scripts":{"dev":"vite","build":"vite build"},"dependencies":{"@vitejs/plugin-react":"latest","@emotion/react":"latest","@emotion/styled":"latest","@mui/material":"latest","axios":"latest","react":"latest","react-dom":"latest"},"devDependencies":{"vite":"latest"}}'; }
function frontendModuleTemplate(entity, segment) { return `import { useEffect, useState } from 'react';\nimport axios from 'axios';\nexport default function ${entity}List(){const [rows,setRows]=useState([]); useEffect(()=>{axios.get('/api/v1/${segment}').then(r=>setRows(r.data));},[]); return <div><h1>${entity}</h1>{rows.map(r=><div key={r.id}>{r.id}</div>)}</div>;}`; }
function compose(mysql) { return mysql ? `services:\n  db:\n    image: mysql:8.4\n    environment:\n      MYSQL_DATABASE: enterprise_db\n      MYSQL_USER: app\n      MYSQL_PASSWORD: app\n      MYSQL_ROOT_PASSWORD: root\n    ports:\n      - "3306:3306"\n` : `services:\n  db:\n    image: postgres:17\n    environment:\n      POSTGRES_DB: enterprise_db\n      POSTGRES_USER: app\n      POSTGRES_PASSWORD: app\n    ports:\n      - "5432:5432"\n`; }
