import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { jwtApplicationPropertiesTemplate, securitySchemaTemplate, securitySeedTemplate, jwtDependencyTemplate } from './jwtRbacTemplates.js';

function safeName(value, fallback = 'generated-app') {
  return String(value || fallback).trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || fallback;
}

function validateSpec(spec) {
  if (!spec?.project?.name) throw new Error('Project name is required');
  if (!spec?.project?.packageName) throw new Error('Java package name is required');
  if (!Array.isArray(spec.modules)) throw new Error('modules must be an array');
}

function moduleKey(module) {
  return safeName(module?.name || module?.key || 'module', 'module');
}

function moduleClass(module) {
  const value = String(module?.name || module?.key || 'Module').replace(/[^A-Za-z0-9]+/g, ' ').trim();
  return value.split(/\s+/).filter(Boolean).map(part => part[0].toUpperCase() + part.slice(1)).join('') || 'Module';
}

function generateCrudMetadata(module) {
  const key = moduleKey(module);
  const fields = (Array.isArray(module?.fields) ? module.fields : []).map(field => ({
    name: field.name || field.key,
    type: field.type || 'string',
    required: Boolean(field.required),
    relation: field.relation || null
  }));
  return {
    key,
    className: moduleClass(module),
    endpoints: {
      list: `/api/v1/${key}`,
      get: `/api/v1/${key}/{id}`,
      create: `/api/v1/${key}`,
      update: `/api/v1/${key}/{id}`,
      delete: `/api/v1/${key}/{id}`
    },
    fields
  };
}

export async function generateProject(spec, outputDir) {
  validateSpec(spec);
  const root = path.resolve(outputDir);
  const backend = path.join(root, 'backend');
  const resources = path.join(backend, 'src/main/resources');
  const migrations = path.join(resources, 'db/migration');
  const frontend = path.join(root, 'frontend/src');
  const moduleMetadata = spec.modules.map(generateCrudMetadata);

  await Promise.all([
    mkdir(migrations, { recursive: true }),
    mkdir(frontend, { recursive: true }),
    mkdir(path.join(frontend, 'modules'), { recursive: true }),
    mkdir(path.join(frontend, 'auth'), { recursive: true }),
    mkdir(path.join(frontend, 'dashboard'), { recursive: true }),
    mkdir(path.join(backend, 'src/main/java'), { recursive: true }),
    mkdir(path.join(root, '.github/workflows'), { recursive: true })
  ]);

  await writeFile(path.join(root, 'generated-project.json'), JSON.stringify(spec, null, 2));
  await writeFile(path.join(root, 'generated-modules.json'), JSON.stringify(moduleMetadata, null, 2));
  await writeFile(path.join(migrations, 'V1__security.sql'), securitySchemaTemplate());
  await writeFile(path.join(migrations, 'V2__security_seed.sql'), securitySeedTemplate());
  await writeFile(path.join(resources, 'application-security.yml'), jwtApplicationPropertiesTemplate());
  await writeFile(path.join(backend, 'JWT_DEPENDENCIES.txt'), jwtDependencyTemplate());

  const dashboardConfig = {
    widgets: moduleMetadata.slice(0, 6).map(module => ({
      type: 'count',
      title: `Total ${module.className}`,
      endpoint: `${module.endpoints.list}?page=0&size=1`
    })),
    dataScopeAware: true
  };
  await writeFile(path.join(frontend, 'dashboard/dashboard.config.json'), JSON.stringify(dashboardConfig, null, 2));
  await writeFile(path.join(frontend, 'modules/modules.config.json'), JSON.stringify(moduleMetadata, null, 2));
  await writeFile(path.join(frontend, 'auth/auth.config.json'), JSON.stringify({ loginEndpoint: '/api/v1/auth/login', tokenType: 'Bearer' }, null, 2));

  for (const module of moduleMetadata) {
    const dir = path.join(frontend, 'modules', module.key);
    await mkdir(dir, { recursive: true });
    await writeFile(path.join(dir, 'module.config.json'), JSON.stringify(module, null, 2));
  }

  await writeFile(path.join(root, 'README.generated.md'), `# ${spec.project.name}\n\nGenerated by Enterprise App Builder.\n\nThe generated frontend exposes editable data grids and forms for configured modules. Backend authorization remains authoritative.\n`);
  return { root, modules: moduleMetadata, dashboard: dashboardConfig };
}

export function generatorPipelineStatus() {
  return {
    status: 'integration-phase',
    capabilities: ['project-spec', 'module-metadata', 'editable-grid-contract', 'dashboard-config', 'jwt-rbac-migrations'],
    next: ['spring-crud-generation', 'react-datagrid-generation', 'zip-validation', 'e2e-tests']
  };
}
