export const JWT_RBAC_MODULE = { name: 'Security', entities: ['User', 'Role', 'Permission'], roles: ['ADMIN', 'USER'] };

export function securityMigrationTemplate(database = 'mysql') {
  const id = database === 'mysql' ? 'BIGINT NOT NULL AUTO_INCREMENT' : 'BIGINT GENERATED BY DEFAULT AS IDENTITY';
  return `CREATE TABLE app_user (id ${id}, username VARCHAR(100) NOT NULL, email VARCHAR(190) NOT NULL, password_hash VARCHAR(255) NOT NULL, enabled BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL, PRIMARY KEY (id), CONSTRAINT uk_app_user_username UNIQUE (username), CONSTRAINT uk_app_user_email UNIQUE (email));
CREATE TABLE app_role (id ${id}, name VARCHAR(80) NOT NULL, PRIMARY KEY (id), CONSTRAINT uk_app_role_name UNIQUE (name));
CREATE TABLE app_permission (id ${id}, name VARCHAR(120) NOT NULL, PRIMARY KEY (id), CONSTRAINT uk_app_permission_name UNIQUE (name));
CREATE TABLE app_user_role (user_id BIGINT NOT NULL, role_id BIGINT NOT NULL, PRIMARY KEY (user_id, role_id), FOREIGN KEY (user_id) REFERENCES app_user(id), FOREIGN KEY (role_id) REFERENCES app_role(id));
CREATE TABLE app_role_permission (role_id BIGINT NOT NULL, permission_id BIGINT NOT NULL, PRIMARY KEY (role_id, permission_id), FOREIGN KEY (role_id) REFERENCES app_role(id), FOREIGN KEY (permission_id) REFERENCES app_permission(id));`;
}

export function securitySeedTemplate() {
  return `INSERT INTO app_role (name) VALUES ('ADMIN'), ('USER');
INSERT INTO app_permission (name) VALUES ('USER_READ'), ('USER_WRITE'), ('USER_DELETE');
INSERT INTO app_role_permission (role_id, permission_id) SELECT r.id, p.id FROM app_role r CROSS JOIN app_permission p WHERE r.name = 'ADMIN';
INSERT INTO app_user (username, email, password_hash, enabled) VALUES ('admin', 'admin@example.com', '{BCRYPT_ADMIN_PASSWORD}', TRUE);
INSERT INTO app_user_role (user_id, role_id) SELECT u.id, r.id FROM app_user u JOIN app_role r ON r.name = 'ADMIN' WHERE u.username = 'admin';`;
}

export function jwtDependenciesTemplate() {
  return `<dependency><groupId>io.jsonwebtoken</groupId><artifactId>jjwt-api</artifactId><version>0.12.7</version></dependency>
<dependency><groupId>io.jsonwebtoken</groupId><artifactId>jjwt-impl</artifactId><version>0.12.7</version><scope>runtime</scope></dependency>
<dependency><groupId>io.jsonwebtoken</groupId><artifactId>jjwt-jackson</artifactId><version>0.12.7</version><scope>runtime</scope></dependency>`;
}

export function authApiContractTemplate() {
  return `POST /api/v1/auth/login\nAuthorization: Bearer <jwt>\n\nRequest: { "username": "admin", "password": "<configured-secret>" }\nResponse: { "accessToken": "<jwt>", "tokenType": "Bearer", "expiresIn": 3600 }`;
}
